{
  description = "Calibre-Web-Automated image";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }: let
    system = builtins.currentSystem;
    pkgs = nixpkgs.legacyPackages.${system};

    # Import the dependency list generated by pip2nix
    deps = (import ./requirements.nix) { inherit pkgs; };

    # ---- CI updates these two lines ----
    cwaRev = "v4.0.6";
    cwaSha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    # -----------------------------------

    src = pkgs.fetchFromGitHub {
      owner = "crocodilestick";
      repo = "Calibre-Web-Automated";
      rev = cwaRev;
      sha256 = cwaSha256;
    };
  in {
    packages.${system}.calibre-web-automated = pkgs.dockerTools.buildLayeredImage {
      name = "calibre-web-automated";
      tag = "latest";
      contents = [
        (pkgs.python3.pkgs.buildPythonApplication {
          pname = "calibre-web-automated";
          version = builtins.substring 1 (builtins.stringLength cwaRev) cwaRev;
          inherit src;
          propagatedBuildInputs = deps;
        })
        pkgs.calibre
        pkgs.kepubify
        pkgs.cacert
        pkgs.tzdata
      ];
      config = {
        Env = [
          "PORT=8083"
          "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt"
        ];
        ExposedPorts = { "8083/tcp" = {}; };
        Volumes = { "/config" = {}; "/books" = {}; };
        Cmd = [ "${pkgs.python3.pkgs.calibre-web-automated}/bin/calibre-web-automated" ];
        User = "1000";
        WorkingDir = "/config";
      };
    };

    # For CI to read the current version
    calibreWebAutomatedVersion = cwaRev;
  };
}
